// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_0h6ZioVnvX5bWBR5ITFvfIypR8-nWw',
    appId: '1:90309820211:web:44ca5ac0a44669b4550846',
    messagingSenderId: '90309820211',
    projectId: 'app-mobile-fcb1b',
    authDomain: 'app-mobile-fcb1b.firebaseapp.com',
    storageBucket: 'app-mobile-fcb1b.appspot.com',
    measurementId: 'G-QL1G1RH6HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9lSIOXkNOrvn8Og2heO13eNxrk1wkXc',
    appId: '1:90309820211:android:943fdcd3a1701b29550846',
    messagingSenderId: '90309820211',
    projectId: 'app-mobile-fcb1b',
    storageBucket: 'app-mobile-fcb1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyAaXkPQj1_xVgJj_5FMJmHA57lOhs1W4',
    appId: '1:90309820211:ios:3d09207bd21489df550846',
    messagingSenderId: '90309820211',
    projectId: 'app-mobile-fcb1b',
    storageBucket: 'app-mobile-fcb1b.appspot.com',
    iosBundleId: 'gn.guinearoads.guineaRoads',
  );
}
